name: torch_env
channels:
  - defaults
dependencies:
  - pip
  - python=3.10.9
  - pip:
    - python-engineio==3.13.2
    - python-socketio==4.6.1
    - eventlet
    - flask
    - flask-socketio
    - numpy
    - opencv-python
    - pillow
    - scikit-learn
    - scipy
    - torch
    - torchaudio
    - torchvision
